"""
Mocked input and output data for lambda
"""


MOCK_GOOD_BBY_RESPONSE = {
    "status_code": 200,
    "json": {
        "ispuEligible": True,
        "stores": [
            {
                "storeID": "1465",
                "name": "Mechanicsville",
                "address": "7297 Battle Hill Dr",
                "city": "Mechanicsville",
                "state": "VA",
                "postalCode": "23111",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 4.5,
            },
            {
                "storeID": "1013",
                "name": "Glen Allen",
                "address": "9901 Brook Rd",
                "city": "Glen Allen",
                "state": "VA",
                "postalCode": "23059",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 9.0,
            },
            {
                "storeID": "422",
                "name": "Chesterfield",
                "address": "1560 W Koger Center Blvd",
                "city": "Richmond",
                "state": "VA",
                "postalCode": "23235",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 12.3,
            },
        ],
    },
}


MOCK_GOOD_RESPONSE = {
    "status": 200,
    "number_of_skus": 4,
    "stock_found": {
        "12345": [
            {
                "storeID": "1465",
                "name": "Mechanicsville",
                "address": "7297 Battle Hill Dr",
                "city": "Mechanicsville",
                "state": "VA",
                "postalCode": "23111",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 4.5,
            },
            {
                "storeID": "1013",
                "name": "Glen Allen",
                "address": "9901 Brook Rd",
                "city": "Glen Allen",
                "state": "VA",
                "postalCode": "23059",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 9.0,
            },
            {
                "storeID": "422",
                "name": "Chesterfield",
                "address": "1560 W Koger Center Blvd",
                "city": "Richmond",
                "state": "VA",
                "postalCode": "23235",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 12.3,
            },
        ],
        "54321": [
            {
                "storeID": "1465",
                "name": "Mechanicsville",
                "address": "7297 Battle Hill Dr",
                "city": "Mechanicsville",
                "state": "VA",
                "postalCode": "23111",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 4.5,
            },
            {
                "storeID": "1013",
                "name": "Glen Allen",
                "address": "9901 Brook Rd",
                "city": "Glen Allen",
                "state": "VA",
                "postalCode": "23059",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 9.0,
            },
            {
                "storeID": "422",
                "name": "Chesterfield",
                "address": "1560 W Koger Center Blvd",
                "city": "Richmond",
                "state": "VA",
                "postalCode": "23235",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 12.3,
            },
        ],
        "90123": [
            {
                "storeID": "1465",
                "name": "Mechanicsville",
                "address": "7297 Battle Hill Dr",
                "city": "Mechanicsville",
                "state": "VA",
                "postalCode": "23111",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 4.5,
            },
            {
                "storeID": "1013",
                "name": "Glen Allen",
                "address": "9901 Brook Rd",
                "city": "Glen Allen",
                "state": "VA",
                "postalCode": "23059",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 9.0,
            },
            {
                "storeID": "422",
                "name": "Chesterfield",
                "address": "1560 W Koger Center Blvd",
                "city": "Richmond",
                "state": "VA",
                "postalCode": "23235",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 12.3,
            },
        ],
        "24601": [
            {
                "storeID": "1465",
                "name": "Mechanicsville",
                "address": "7297 Battle Hill Dr",
                "city": "Mechanicsville",
                "state": "VA",
                "postalCode": "23111",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 4.5,
            },
            {
                "storeID": "1013",
                "name": "Glen Allen",
                "address": "9901 Brook Rd",
                "city": "Glen Allen",
                "state": "VA",
                "postalCode": "23059",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 9.0,
            },
            {
                "storeID": "422",
                "name": "Chesterfield",
                "address": "1560 W Koger Center Blvd",
                "city": "Richmond",
                "state": "VA",
                "postalCode": "23235",
                "storeType": "Self_Delivery_Store",
                "minPickupHours": None,
                "lowStock": False,
                "distance": 12.3,
            },
        ],
    },
    "error": "",
}
